### ISSUE TITLE
Text near impossible to read due to CSS rules

### ISSUE THREAD

**Issue by exurd** [pizzaboxer/roblox-set-archive#1] opened 2024-07-31 12:37 UTC
The current CSS on the website makes some text nearly impossible to read.

![screenshot 1 of website](https://github.com/user-attachments/assets/eae860e4-bb16-4b40-afaf-2491472c06f2)

![screenshot 2 of website](https://github.com/user-attachments/assets/a03ee7d6-044b-40b3-bfcd-631b659171d8)

**Comment by pizzaboxer** [comment] 2024-07-31 12:57
I actually forgot this issue existed - it's because the dark theme rules aren't properly applying in some circumstances. I'll try to fix it, though it'll be sort of difficult since I can't really reproduce it.

**Comment by exurd** [comment] 2024-07-31 13:06
> it's because the dark theme rules aren't properly applying in some circumstances.

~~I'm currently in light mode and when I switch to dark mode it looks as it should, so it can't be that.~~ (Edit 19:05 - Okay, it seems to be a part of the issue.)

However, I did find something in the HTML:
https://github.com/pizzaboxer/roblox-set-archive/blob/d3a48269d95682e10afde54f034971a44ad588e2/RobloxSetArchive.Web/index.html#L19

Removing it from the body fixes the text issue, though the navbar is still a bit funky.
![screenshot 3 of website](https://github.com/user-attachments/assets/dd956037-b2a5-4242-9290-adfd2189a54c)

**Comment by pizzaboxer** [comment] 2024-07-31 18:18
Should be all fixed now

**Closed as completed by pizzaboxer** 2024-07-31 18:18 UTC
